Don't include both linux/prctl.h and sys/prctl.h
see https://www.openwall.com/lists/musl/2025/06/12/11

c++ -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -fno-plt  -O2 -c -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -fPIE -Wformat -Wformat-security -Wno-format-nonliteral -Wall -Wextra -Werror -Ikafel/include -DPROTOBUF_USE_DLLS -DNOMINMAX -std=c++20 -fno-exceptions -Wno-unused -Wno-unused-parameter -I/usr/include/libnl3 subproc.cc -o subproc.o
In file included from net.cc:39:
/usr/include/sys/prctl.h:88:8: error: redefinition of 'struct prctl_mm_map'
   88 | struct prctl_mm_map {
      |        ^~~~~~~~~~~~
In file included from net.cc:27:
/usr/include/linux/prctl.h:134:8: note: previous definition of 'struct prctl_mm_map'
  134 | struct prctl_mm_map {
      |