net.cc: Add missing include
c++ -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -fno-plt  -O2 -c -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -fPIE -Wformat -Wformat-security -Wno-format-nonliteral -Wall -Wextra -Werror -Ikafel/include -DPROTOBUF_USE_DLLS -DNOMINMAX -std=c++20 -fno-exceptions -Wno-unused -Wno-unused-parameter -I/usr/include/libnl3 subproc.cc -o subproc.o
net.cc: In function 'bool net::spawnPasta(nsj_t*, int)':
net.cc:259:30: error: 'TEMP_FAILURE_RETRY' was not declared in this scope
  259 |                 int nullfd = TEMP_FAILURE_RETRY(open("/dev/null", O_RDWR));
      |

--

TEMP_FAILURE_RETRY macros is defined in macros.h